version: 2.4

services:
  vk2tg:
    build:
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      Vk2Tg_TelegramToken: token
      Vk2Tg_TelegramChatId: 0
      Vk2Tg_GmailEmail: example@gmail.com
      Vk2Tg_GmailPassword: password
      Vk2Tg_VkToken: token
      Vk2Tg_VkGroupId: 0